# Couleurs par défaut — remplacées par matugen image <wallpaper>
# target                  title      bg         text       indicator  border
client.focused            #89b4fa    #1e1e2e    #cdd6f4    #89b4fa    #89b4fa
client.focused_inactive   #313244    #1e1e2e    #cdd6f4    #313244    #313244
client.unfocused          #313244    #1e1e2e    #cdd6f4    #313244    #313244
client.urgent             #f38ba8    #1e1e2e    #f38ba8    #313244    #f38ba8
client.placeholder        #313244    #1e1e2e    #cdd6f4    #313244    #313244

set $client.background #1e1e2e
